// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMcT-LiPjVpsUEdBG8xJyRsA7AiiB3YfY',
    appId: '1:965858215724:web:dc39fb5eb5666c6e0c0e89',
    messagingSenderId: '965858215724',
    projectId: 'weev-app',
    authDomain: 'weev-app.firebaseapp.com',
    storageBucket: 'weev-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZCMX0BNJLz3iyDRcI2_e7ciiWpB2pOdc',
    appId: '1:965858215724:android:a27e2666d47b74bc0c0e89',
    messagingSenderId: '965858215724',
    projectId: 'weev-app',
    storageBucket: 'weev-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9HBmiwQyj_5Eh-dFwYOo0wOzqxyjUekM',
    appId: '1:965858215724:ios:ecdaaf4b9e17fae40c0e89',
    messagingSenderId: '965858215724',
    projectId: 'weev-app',
    storageBucket: 'weev-app.firebasestorage.app',
    iosClientId: '965858215724-vb5hv9mf5ojr9jp960dlqcud6tmhqh3e.apps.googleusercontent.com',
    iosBundleId: 'com.weev.app.weevApp',
  );
}
