// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYtkH31d5_uREDxPMkBRtneW5-Qvm-Avc',
    appId: '1:504564088502:web:c53402fac7c4b9c902f017',
    messagingSenderId: '504564088502',
    projectId: 'weev-27124',
    authDomain: 'weev-27124.firebaseapp.com',
    storageBucket: 'weev-27124.firebasestorage.app',
    measurementId: 'G-QXP8JWGSES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpnVDacT4Sf9C4tvwZVZS77NBLkujIF9o',
    appId: '1:504564088502:android:e365959efb91923102f017',
    messagingSenderId: '504564088502',
    projectId: 'weev-27124',
    storageBucket: 'weev-27124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgZRMzO25BtfStvp9FF4pAJbCsVM_bPEs',
    appId: '1:504564088502:ios:def1ff5aa50ec3e902f017',
    messagingSenderId: '504564088502',
    projectId: 'weev-27124',
    storageBucket: 'weev-27124.firebasestorage.app',
    iosBundleId: 'com.example.weevApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZRMzO25BtfStvp9FF4pAJbCsVM_bPEs',
    appId: '1:504564088502:ios:def1ff5aa50ec3e902f017',
    messagingSenderId: '504564088502',
    projectId: 'weev-27124',
    storageBucket: 'weev-27124.firebasestorage.app',
    iosBundleId: 'com.example.weevApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYtkH31d5_uREDxPMkBRtneW5-Qvm-Avc',
    appId: '1:504564088502:web:63cdf394ae8d6bc902f017',
    messagingSenderId: '504564088502',
    projectId: 'weev-27124',
    authDomain: 'weev-27124.firebaseapp.com',
    storageBucket: 'weev-27124.firebasestorage.app',
    measurementId: 'G-SCJW4WY190',
  );
}
